version: '3.7'

services:

    nginx:
        build:
            context: ./docker/nginx
        ports:
            - "80:8083"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        user: user
        networks:
            - backend
        links:
            - php

    php:
        build:
            context: ./docker/php
        image: 'laravelapp'
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ~/.ssh/id_rsa.pub:/home/user/.ssh/id_rsa.pub
        user: user
        environment:
            PHP_IDE_CONFIG: "serverName=spisok"
        networks:
            - backend
        links:
            - rabbitmq

    worker:
        build:
            context: ./docker/worker
        image: 'laravelworker'
        volumes:
            - .:/var/www/html
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
            - ./docker/worker/conf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
            - ~/.ssh/id_rsa.pub:/home/user/.ssh/id_rsa.pub
        user: user
        #command: [ "supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf" ]
        networks:
            - backend
        links:
            - rabbitmq

    redis:
        build: ./docker/redis
        container_name: redis
        command: redis-server --appendonly yes
        volumes:
            - ./docker/redis/data:/data
        ports:
            - "8002:6379"
        networks:
            - backend

    rabbitmq:
        image: rabbitmq:3.9-management
        container_name: rabbitmq-avangard
        ports:
            - "15672:15672"
        volumes:
            - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia/
        networks:
            backend:
                aliases:
                    - rabbitmq

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'list'
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'default'
            MYSQL_PASSWORD: 'secret'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
            - ./docker/mysql/log/mysql.log:/var/log/mysql/mysql.log
        networks:
            - backend

networks:
    backend:
        driver: bridge
